### ISSUE TITLE
'prospective_power' is not an exported object from 'namespace:MarketMatching'

### ISSUE THREAD

**Issue by iprice-sam** [klarsen1/MarketMatching#22]
I just installed MarketMatching from github and tried running the sample code for Pseudo Power Curves: https://github.com/klarsen1/MarketMatching#prospective-pseudo-power-curves

I get the following error: 

Error: 'prospective_power' is not an exported object from 'namespace:MarketMatching'

Any ideas?

**Comment by klarsen1** [comment]
Good catch. The readme is out of date. I'll update it.

I'll fix it. Also, the package is in CRAN. I'd use that one instead and
check out the vignette instead of the readme.

The correct code looks like this. The function is called test_fake_lift(():

 power <- MarketMatching::test_fake_lift(matched_markets = rollup,
                        test_market = "TEST",
                        end_fake_post_period = "2015-10-01",
                        lift_pattern_type = "constant",
                        steps=20,
                        max_fake_lift = 0.05)

**Comment by iprice-sam** [comment]
Got it. Thanks!
