### ISSUE TITLE
How to Leave Out Dates from Training and Inference for Validation?

### ISSUE THREAD

**Issue by sssiv93** [klarsen1/MarketMatching#27]
Does MarketMatching allow you to select a post period start date when running inference? I would ideally like to use best_matches to identify some good control markets over a training period, and then test out whether the correlation still holds on a validation period. In order to do this, I need to leave out some dates between the matching period and the inference period. Is there a way to do this? Thank you.

**Comment by klarsen1** [comment]
Yes and no.

The package allows you to choose your matching period using the
start_match_period and end_match_period parameters. Then, when you do
inference based on the markets you selected, you can see how well the model
fits in the training period (that's what determines confidence for the post
period inference). Checking market fits in the post period makes no sense
for inference since the entire point of inference is to measure test versus
control divergence (or lack of) in the post period.

If you want to use the package as a general matching utility (and not post
period test versus control inference), it does not provide a holdout
correlation feature, you'd have to export the markets and check that
yourself.

Kim

**Comment by sssiv93** [comment]
Thank you, Kim. I wondered if I could ask you one more question (let me know if you would like me to create a new issue for this). 

Do you have any guidance on what values are typically selected for the warping limit? I am trying to do some sensitivity analysis to observe how changing the parameters affects the estimated impact.

**Comment by klarsen1** [comment]
I keep the limits narrow— like 2 or so. Unless you have shifting time
series you don’t really even need warping tbh. In fact, you can set
dtw_emphasis to zero

**Comment by sssiv93** [comment]
Thanks!
